export default () => ({
  allPosts: [],
  singlePost: {},
  users: [],
  addFreind: [],
  myRequests: [],
  myFreindsRequests: [],
  myFreinds: [],
  deleteMyRequest: {},
  acceptFreindsRequest: {},
  rejectFreindsRequest: {},
  blockMyFreind: {},
  // for posts [add like , share, comment etc]
  addPost: [],
  addPostLike: [],
  allPostLikes: [],
  sharePost: {},
  allPostComments: [],
  singleComment: {},
  addComment: [],
  addReplay: {},
  getLikesNumber: "",
  // chatt
  chooseFreind: {},
});
